***Adaboost Classifier***  
https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.AdaBoostClassifier.html

# **Data Preprocessing**

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [5]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Datasets For Machine Learning/diabetes_two (1).csv')
#df.head()

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Age                 519 non-null    float64
 1   Gender              519 non-null    object 
 2   Polyuria            520 non-null    object 
 3   Polydipsia          520 non-null    object 
 4   sudden weight loss  520 non-null    object 
 5   weakness            519 non-null    object 
 6   Polyphagia          520 non-null    object 
 7   Genital thrush      520 non-null    object 
 8   visual blurring     520 non-null    object 
 9   Itching             520 non-null    object 
 10  Irritability        520 non-null    object 
 11  delayed healing     520 non-null    object 
 12  partial paresis     520 non-null    object 
 13  muscle stiffness    520 non-null    object 
 14  Alopecia            520 non-null    object 
 15  Obesity             520 non-null    object 
 16  class   

In [7]:
df.isnull().sum() #finding null values

Age                   1
Gender                1
Polyuria              0
Polydipsia            0
sudden weight loss    0
weakness              1
Polyphagia            0
Genital thrush        0
visual blurring       0
Itching               0
Irritability          0
delayed healing       0
partial paresis       0
muscle stiffness      0
Alopecia              0
Obesity               0
class                 0
dtype: int64

In [8]:
df['weakness']

0      Yes
1      Yes
2      Yes
3      Yes
4      Yes
      ... 
515     No
516    Yes
517    Yes
518    Yes
519     No
Name: weakness, Length: 520, dtype: object

In [9]:
df['Age'] = df['Age'].fillna(df['Age'].mean())  #Handling null values
df['Gender'] = df['Gender'].fillna(df['Gender'].mode().iloc[0])
df['weakness'] = df['weakness'].fillna(df['weakness'].mode().iloc[0])

In [10]:
df.isnull().sum()

Age                   0
Gender                0
Polyuria              0
Polydipsia            0
sudden weight loss    0
weakness              0
Polyphagia            0
Genital thrush        0
visual blurring       0
Itching               0
Irritability          0
delayed healing       0
partial paresis       0
muscle stiffness      0
Alopecia              0
Obesity               0
class                 0
dtype: int64

In [11]:
#Encoding categorical data
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [12]:
df['Gender'] = le.fit_transform(df['Gender']) # converting the categorical data into numerical
df['Polyuria'] = le.fit_transform(df['Polyuria'])
df['Polydipsia'] = le.fit_transform(df['Polydipsia'])
df['sudden weight loss'] = le.fit_transform(df['sudden weight loss'])
df['weakness'] = le.fit_transform(df['weakness'])
df['Polyphagia'] = le.fit_transform(df['Polyphagia'])
df['Genital thrush'] = le.fit_transform(df['Genital thrush'])
df['visual blurring'] = le.fit_transform(df['visual blurring'])
df['Itching'] = le.fit_transform(df['Itching'])
df['Irritability'] = le.fit_transform(df['Irritability'])
df['delayed healing'] = le.fit_transform(df['delayed healing'])
df['partial paresis'] = le.fit_transform(df['partial paresis'])
df['muscle stiffness'] = le.fit_transform(df['muscle stiffness'])
df['Alopecia'] = le.fit_transform(df['Alopecia'])
df['Obesity'] = le.fit_transform(df['Obesity'])
df['class'] = le.fit_transform(df['class'])

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Age                 520 non-null    float64
 1   Gender              520 non-null    int64  
 2   Polyuria            520 non-null    int64  
 3   Polydipsia          520 non-null    int64  
 4   sudden weight loss  520 non-null    int64  
 5   weakness            520 non-null    int64  
 6   Polyphagia          520 non-null    int64  
 7   Genital thrush      520 non-null    int64  
 8   visual blurring     520 non-null    int64  
 9   Itching             520 non-null    int64  
 10  Irritability        520 non-null    int64  
 11  delayed healing     520 non-null    int64  
 12  partial paresis     520 non-null    int64  
 13  muscle stiffness    520 non-null    int64  
 14  Alopecia            520 non-null    int64  
 15  Obesity             520 non-null    int64  
 16  class   

In [14]:
#Handling outliers
z_score =(df['Age'] - df["Age"].mean())/df['Age'].std()
for i in z_score:
  if i<-3 or i>3:
    print("You have outlier",i)
    o_val = i
  else:
    continue

index = z_score.index[z_score == o_val][0]
df['Age'][index]

You have outlier 20.34563622506856


np.float64(600.0)

In [15]:
df["Age"][index] = df['Age'].mean()

<ipython-input-15-2678756924>:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["Age"][index] = df['Age'].mean()
<ipython-input-15-2678756924>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

S

In [16]:
df['Age'][index]

np.float64(49.08285163776493)

In [17]:
#Handling duplicates
#duplicates = df[df.duplicated(keep="first")]
#duplicates

In [18]:
#df = df.drop_duplicates()

In [19]:
#duplicates = df[df.duplicated(keep="first")]
#duplicates

In [20]:
import matplotlib.pyplot as plt #for plotting
import seaborn as sns

In [21]:
#sns.set(font_scale=2)
#plt.subplots(figsize=(20,20))
#heat_plot=sns.heatmap(df.corr(method='pearson'),annot=True,cmap='RdYlGn',annot_kws={'size':20}) #Pearson correlation / heatmap

#plt.yticks(fontsize =35) # font size of y axis
#plt.xticks(fontsize =35) # font size of x axis

#plt.show()

We can opt out itching

In [22]:
#Finding exact correlation values by descending order
correlations =df.corr(method='pearson')['class'].sort_values(ascending=False)
correlations

class                 1.000000
Polyuria              0.665922
Polydipsia            0.648734
sudden weight loss    0.436568
partial paresis       0.432288
Polyphagia            0.342504
Irritability          0.299467
visual blurring       0.251300
weakness              0.243275
muscle stiffness      0.122474
Genital thrush        0.110288
Age                   0.108459
Obesity               0.072173
delayed healing       0.046980
Itching              -0.013384
Alopecia             -0.267512
Gender               -0.449233
Name: class, dtype: float64

In [23]:
#df.dropna(subset=['Itching'],inplace = True)

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Age                 520 non-null    float64
 1   Gender              520 non-null    int64  
 2   Polyuria            520 non-null    int64  
 3   Polydipsia          520 non-null    int64  
 4   sudden weight loss  520 non-null    int64  
 5   weakness            520 non-null    int64  
 6   Polyphagia          520 non-null    int64  
 7   Genital thrush      520 non-null    int64  
 8   visual blurring     520 non-null    int64  
 9   Itching             520 non-null    int64  
 10  Irritability        520 non-null    int64  
 11  delayed healing     520 non-null    int64  
 12  partial paresis     520 non-null    int64  
 13  muscle stiffness    520 non-null    int64  
 14  Alopecia            520 non-null    int64  
 15  Obesity             520 non-null    int64  
 16  class   

In [25]:
df

Age  Gender  Polyuria  Polydipsia  sudden weight loss  weakness  \
0    40.000000       1         0           1                   0         1   
1    58.000000       1         0           0                   0         1   
2    49.082852       1         1           0                   0         1   
3    45.000000       1         0           0                   1         1   
4    49.082852       1         1           1                   1         1   
..         ...     ...       ...         ...                 ...       ...   
515  39.000000       0         1           1                   1         0   
516  48.000000       0         1           1                   1         1   
517  58.000000       0         1           1                   1         1   
518  32.000000       0         0           0                   0         1   
519  42.000000       1         0           0                   0         0   

     Polyphagia  Genital thrush  visual blurring  Itching  Irritability  \
0             0               0                0        1             0   
1             0               0                1        0             0   
2             1               0                0        1             0   
3             1               1                0        1             0   
4             1               0                1        1             1   
..          ...             ...              ...      ...           ...   
515           1               0                0        1             0   
516           1               0                0        1             1   
517           1               0                1        0             0   
518           0               0                1        1             0   
519           0               0                0        0             0   

     delayed healing  partial paresis  muscle stiffness  Alopecia  Obesity  \
0                  1                0                 1         1        1   
1                  0                1                 0         1        0   
2                  1                0                 1         1        0   
3                  1                0                 0         0        0   
4                  1                1                 1         1        1   
..               ...              ...               ...       ...      ...   
515                1                1                 0         0        0   
516                1                1                 0         0        0   
517                0                1                 1         0        1   
518                1                0                 0         1        0   
519                0                0                 0         0        0   

     class  
0        1  
1        1  
2        1  
3        1  
4        1  
..     ...  
515      1  
516      1  
517      1  
518      0  
519      0  

[520 rows x 17 columns]

In [26]:
# Shuffling the dataset
from sklearn.utils import shuffle
df = shuffle(df)

In [27]:
#re-arranging the index values
df = df.reset_index(drop=True)
df

Age  Gender  Polyuria  Polydipsia  sudden weight loss  weakness  \
0    63.0       1         1           1                   1         1   
1    48.0       1         1           1                   1         0   
2    55.0       1         1           1                   1         1   
3    39.0       0         1           1                   1         1   
4    50.0       0         0           1                   1         1   
..    ...     ...       ...         ...                 ...       ...   
515  36.0       1         0           0                   0         0   
516  64.0       1         0           0                   0         1   
517  55.0       1         1           1                   1         1   
518  42.0       1         1           1                   0         1   
519  27.0       1         0           0                   0         0   

     Polyphagia  Genital thrush  visual blurring  Itching  Irritability  \
0             1               0                1        0             0   
1             1               1                0        0             0   
2             0               1                0        0             1   
3             1               0                0        1             1   
4             0               0                1        0             0   
..          ...             ...              ...      ...           ...   
515           0               0                0        0             0   
516           1               0                1        1             1   
517           1               0                1        0             0   
518           0               1                0        0             1   
519           0               0                0        0             0   

     delayed healing  partial paresis  muscle stiffness  Alopecia  Obesity  \
0                  0                0                 1         1        1   
1                  1                0                 0         0        0   
2                  0                1                 0         0        0   
3                  1                1                 0         0        0   
4                  1                0                 0         0        0   
..               ...              ...               ...       ...      ...   
515                0                0                 0         0        0   
516                1                0                 1         1        0   
517                1                1                 0         0        0   
518                0                1                 0         1        0   
519                0                0                 0         0        0   

     class  
0        1  
1        1  
2        1  
3        1  
4        1  
..     ...  
515      0  
516      0  
517      1  
518      1  
519      0  

[520 rows x 17 columns]

In [28]:
#Separating feature and Target
x = df.drop(columns=['class']) #feature
y = df['class']   #target

In [29]:
#Scaling data
from sklearn.preprocessing import MinMaxScaler,StandardScaler  #not necessary for decision tree
mm = MinMaxScaler()
x = mm.fit_transform(x)
#sc = StandardScaler()
#x = sc.fit_transform(x)
x

array([[0.63513514, 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [0.43243243, 1.        , 1.        , ..., 0.        , 0.        ,
        0.        ],
       [0.52702703, 1.        , 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.52702703, 1.        , 1.        , ..., 0.        , 0.        ,
        0.        ],
       [0.35135135, 1.        , 1.        , ..., 0.        , 1.        ,
        0.        ],
       [0.14864865, 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [30]:
#Splitting data
#from sklearn.model_selection import train_test_split
#x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [31]:
#print("train data size (features):",len(x_train))
#print("train data size (target):",len(y_train))

#print("test data size (features):",len(x_test))
#print("test data size (target):",len(y_test))

# <font color = 'orange'> <font size = 5> <b> Model

In [44]:
from sklearn.ensemble import AdaBoostClassifier
adaboost = AdaBoostClassifier(estimator=None, n_estimators=100, learning_rate=1.0, random_state=0)

In [45]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold

k_fold = KFold(10)

accuracy = cross_val_score(adaboost,x,y,cv=k_fold,scoring='accuracy')
precision = cross_val_score(adaboost,x,y,cv=k_fold,scoring='precision')
recall = cross_val_score(adaboost,x,y,cv=k_fold,scoring='recall')
f1_score = cross_val_score(adaboost,x,y,cv=k_fold,scoring='f1')
AUC = cross_val_score(adaboost,x,y,cv=k_fold,scoring='roc_auc')

In [46]:
accuracy

array([0.94230769, 0.98076923, 0.88461538, 0.94230769, 0.96153846,
       0.88461538, 0.82692308, 0.94230769, 0.96153846, 0.94230769])

In [47]:
# average accuracy
overall_accuracy = sum(accuracy)/ len(accuracy)
print(overall_accuracy)

0.9269230769230768


In [48]:
precision

array([0.96875   , 0.97058824, 0.90322581, 0.9375    , 0.96969697,
       0.93548387, 0.93333333, 0.92592593, 1.        , 0.96666667])

In [49]:
overall_precision = sum(precision)/ len(precision)
print(overall_precision)

0.9511170808336369


In [50]:
recall

array([0.93939394, 1.        , 0.90322581, 0.96774194, 0.96969697,
       0.87878788, 0.8       , 0.96153846, 0.94117647, 0.93548387])

In [51]:
overall_recall = sum(recall)/ len(recall)
print(overall_recall)

0.9297045332908711


In [52]:
f1_score

array([0.95384615, 0.98507463, 0.90322581, 0.95238095, 0.96969697,
       0.90625   , 0.86153846, 0.94339623, 0.96969697, 0.95081967])

In [53]:
overall_f1_score = sum(f1_score)/ len(f1_score)
print(overall_f1_score)

0.9395925839023034


In [54]:
AUC

array([0.99521531, 0.99681021, 0.95084485, 0.98310292, 0.98564593,
       0.98086124, 0.92941176, 0.99408284, 0.98202614, 0.98617512])

In [55]:
overall_AUC = sum(AUC)/ len(AUC)
print(overall_AUC)

0.9784176331973043
