# **Data Preprocessing**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Datasets For Machine Learning/diabetes_two (1).csv')
#df.head()

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Age                 519 non-null    float64
 1   Gender              519 non-null    object 
 2   Polyuria            520 non-null    object 
 3   Polydipsia          520 non-null    object 
 4   sudden weight loss  520 non-null    object 
 5   weakness            519 non-null    object 
 6   Polyphagia          520 non-null    object 
 7   Genital thrush      520 non-null    object 
 8   visual blurring     520 non-null    object 
 9   Itching             520 non-null    object 
 10  Irritability        520 non-null    object 
 11  delayed healing     520 non-null    object 
 12  partial paresis     520 non-null    object 
 13  muscle stiffness    520 non-null    object 
 14  Alopecia            520 non-null    object 
 15  Obesity             520 non-null    object 
 16  class   

In [4]:
df.isnull().sum() #finding null values

Age                   1
Gender                1
Polyuria              0
Polydipsia            0
sudden weight loss    0
weakness              1
Polyphagia            0
Genital thrush        0
visual blurring       0
Itching               0
Irritability          0
delayed healing       0
partial paresis       0
muscle stiffness      0
Alopecia              0
Obesity               0
class                 0
dtype: int64

In [5]:
df['weakness']

0      Yes
1      Yes
2      Yes
3      Yes
4      Yes
      ... 
515     No
516    Yes
517    Yes
518    Yes
519     No
Name: weakness, Length: 520, dtype: object

In [6]:
df['Age'] = df['Age'].fillna(df['Age'].mean())  #Handling null values
df['Gender'] = df['Gender'].fillna(df['Gender'].mode().iloc[0])
df['weakness'] = df['weakness'].fillna(df['weakness'].mode().iloc[0])

In [7]:
df.isnull().sum()

Age                   0
Gender                0
Polyuria              0
Polydipsia            0
sudden weight loss    0
weakness              0
Polyphagia            0
Genital thrush        0
visual blurring       0
Itching               0
Irritability          0
delayed healing       0
partial paresis       0
muscle stiffness      0
Alopecia              0
Obesity               0
class                 0
dtype: int64

In [8]:
#Encoding categorical data
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [9]:
df['Gender'] = le.fit_transform(df['Gender']) # converting the categorical data into numerical
df['Polyuria'] = le.fit_transform(df['Polyuria'])
df['Polydipsia'] = le.fit_transform(df['Polydipsia'])
df['sudden weight loss'] = le.fit_transform(df['sudden weight loss'])
df['weakness'] = le.fit_transform(df['weakness'])
df['Polyphagia'] = le.fit_transform(df['Polyphagia'])
df['Genital thrush'] = le.fit_transform(df['Genital thrush'])
df['visual blurring'] = le.fit_transform(df['visual blurring'])
df['Itching'] = le.fit_transform(df['Itching'])
df['Irritability'] = le.fit_transform(df['Irritability'])
df['delayed healing'] = le.fit_transform(df['delayed healing'])
df['partial paresis'] = le.fit_transform(df['partial paresis'])
df['muscle stiffness'] = le.fit_transform(df['muscle stiffness'])
df['Alopecia'] = le.fit_transform(df['Alopecia'])
df['Obesity'] = le.fit_transform(df['Obesity'])
df['class'] = le.fit_transform(df['class'])

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Age                 520 non-null    float64
 1   Gender              520 non-null    int64  
 2   Polyuria            520 non-null    int64  
 3   Polydipsia          520 non-null    int64  
 4   sudden weight loss  520 non-null    int64  
 5   weakness            520 non-null    int64  
 6   Polyphagia          520 non-null    int64  
 7   Genital thrush      520 non-null    int64  
 8   visual blurring     520 non-null    int64  
 9   Itching             520 non-null    int64  
 10  Irritability        520 non-null    int64  
 11  delayed healing     520 non-null    int64  
 12  partial paresis     520 non-null    int64  
 13  muscle stiffness    520 non-null    int64  
 14  Alopecia            520 non-null    int64  
 15  Obesity             520 non-null    int64  
 16  class   

In [11]:
#Handling outliers
z_score =(df['Age'] - df["Age"].mean())/df['Age'].std()
for i in z_score:
  if i<-3 or i>3:
    print("You have outlier",i)
    o_val = i
  else:
    continue

index = z_score.index[z_score == o_val][0]
df['Age'][index]

You have outlier 20.34563622506856


np.float64(600.0)

In [12]:
df["Age"][index] = df['Age'].mean()

<ipython-input-12-9fa035bd217d>:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["Age"][index] = df['Age'].mean()
<ipython-input-12-9fa035bd217d>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFram

In [13]:
df['Age'][index]

np.float64(49.08285163776493)

In [14]:
#Handling duplicates
#duplicates = df[df.duplicated(keep="first")]
#duplicates

In [15]:
#df = df.drop_duplicates()

In [16]:
#duplicates = df[df.duplicated(keep="first")]
#duplicates

In [17]:
import matplotlib.pyplot as plt #for plotting
import seaborn as sns

In [18]:
#sns.set(font_scale=2)
#plt.subplots(figsize=(20,20))
#heat_plot=sns.heatmap(df.corr(method='pearson'),annot=True,cmap='RdYlGn',annot_kws={'size':20}) #Pearson correlation / heatmap

#plt.yticks(fontsize =35) # font size of y axis
#plt.xticks(fontsize =35) # font size of x axis

#plt.show()

We can opt out itching

In [19]:
#Finding exact correlation values by descending order
correlations =df.corr(method='pearson')['class'].sort_values(ascending=False)
correlations

class                 1.000000
Polyuria              0.665922
Polydipsia            0.648734
sudden weight loss    0.436568
partial paresis       0.432288
Polyphagia            0.342504
Irritability          0.299467
visual blurring       0.251300
weakness              0.243275
muscle stiffness      0.122474
Genital thrush        0.110288
Age                   0.108459
Obesity               0.072173
delayed healing       0.046980
Itching              -0.013384
Alopecia             -0.267512
Gender               -0.449233
Name: class, dtype: float64

In [20]:
#df.dropna(subset=['Itching'],inplace = True)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Age                 520 non-null    float64
 1   Gender              520 non-null    int64  
 2   Polyuria            520 non-null    int64  
 3   Polydipsia          520 non-null    int64  
 4   sudden weight loss  520 non-null    int64  
 5   weakness            520 non-null    int64  
 6   Polyphagia          520 non-null    int64  
 7   Genital thrush      520 non-null    int64  
 8   visual blurring     520 non-null    int64  
 9   Itching             520 non-null    int64  
 10  Irritability        520 non-null    int64  
 11  delayed healing     520 non-null    int64  
 12  partial paresis     520 non-null    int64  
 13  muscle stiffness    520 non-null    int64  
 14  Alopecia            520 non-null    int64  
 15  Obesity             520 non-null    int64  
 16  class   

In [22]:
df

Age  Gender  Polyuria  Polydipsia  sudden weight loss  weakness  \
0    40.000000       1         0           1                   0         1   
1    58.000000       1         0           0                   0         1   
2    49.082852       1         1           0                   0         1   
3    45.000000       1         0           0                   1         1   
4    49.082852       1         1           1                   1         1   
..         ...     ...       ...         ...                 ...       ...   
515  39.000000       0         1           1                   1         0   
516  48.000000       0         1           1                   1         1   
517  58.000000       0         1           1                   1         1   
518  32.000000       0         0           0                   0         1   
519  42.000000       1         0           0                   0         0   

     Polyphagia  Genital thrush  visual blurring  Itching  Irritability  \
0             0               0                0        1             0   
1             0               0                1        0             0   
2             1               0                0        1             0   
3             1               1                0        1             0   
4             1               0                1        1             1   
..          ...             ...              ...      ...           ...   
515           1               0                0        1             0   
516           1               0                0        1             1   
517           1               0                1        0             0   
518           0               0                1        1             0   
519           0               0                0        0             0   

     delayed healing  partial paresis  muscle stiffness  Alopecia  Obesity  \
0                  1                0                 1         1        1   
1                  0                1                 0         1        0   
2                  1                0                 1         1        0   
3                  1                0                 0         0        0   
4                  1                1                 1         1        1   
..               ...              ...               ...       ...      ...   
515                1                1                 0         0        0   
516                1                1                 0         0        0   
517                0                1                 1         0        1   
518                1                0                 0         1        0   
519                0                0                 0         0        0   

     class  
0        1  
1        1  
2        1  
3        1  
4        1  
..     ...  
515      1  
516      1  
517      1  
518      0  
519      0  

[520 rows x 17 columns]

In [23]:
# Shuffling the dataset
from sklearn.utils import shuffle
df = shuffle(df)

In [24]:
#re-arranging the index values
df = df.reset_index(drop=True)
df

Age  Gender  Polyuria  Polydipsia  sudden weight loss  weakness  \
0    43.0       1         1           1                   1         1   
1    56.0       1         1           0                   1         1   
2    85.0       1         1           1                   1         1   
3    39.0       1         1           0                   1         0   
4    48.0       0         0           0                   1         1   
..    ...     ...       ...         ...                 ...       ...   
515  43.0       0         1           1                   1         1   
516  42.0       1         1           1                   0         1   
517  34.0       0         0           0                   1         0   
518  52.0       1         1           1                   1         1   
519  48.0       0         1           1                   0         1   

     Polyphagia  Genital thrush  visual blurring  Itching  Irritability  \
0             0               1                0        0             0   
1             0               1                0        1             1   
2             1               1                1        1             0   
3             0               1                0        1             1   
4             0               0                1        1             0   
..          ...             ...              ...      ...           ...   
515           1               0                1        0             0   
516           0               1                0        0             1   
517           0               0                0        0             0   
518           1               0                1        1             0   
519           0               0                1        1             0   

     delayed healing  partial paresis  muscle stiffness  Alopecia  Obesity  \
0                  0                0                 0         0        0   
1                  0                0                 0         1        0   
2                  1                1                 1         0        0   
3                  0                0                 0         1        0   
4                  1                1                 0         0        0   
..               ...              ...               ...       ...      ...   
515                0                1                 1         0        1   
516                0                1                 0         1        0   
517                0                0                 0         0        0   
518                1                1                 1         0        0   
519                1                1                 0         0        0   

     class  
0        1  
1        1  
2        1  
3        1  
4        1  
..     ...  
515      1  
516      1  
517      0  
518      1  
519      1  

[520 rows x 17 columns]

In [25]:
#Separating feature and Target
x = df.drop(columns=['class']) #feature
y = df['class']   #target

In [26]:
#Scaling data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)
x

array([[-4.14311681e-01,  7.65092056e-01,  1.00772212e+00, ...,
        -7.74596669e-01, -7.24518244e-01, -4.51335467e-01],
       [ 6.57881771e-01,  7.65092056e-01,  1.00772212e+00, ...,
        -7.74596669e-01,  1.38022749e+00, -4.51335467e-01],
       [ 3.04969793e+00,  7.65092056e-01,  1.00772212e+00, ...,
         1.29099445e+00, -7.24518244e-01, -4.51335467e-01],
       ...,
       [-1.15659945e+00, -1.30703226e+00, -9.92337052e-01, ...,
        -7.74596669e-01, -7.24518244e-01, -4.51335467e-01],
       [ 3.27976093e-01,  7.65092056e-01,  1.00772212e+00, ...,
         1.29099445e+00, -7.24518244e-01, -4.51335467e-01],
       [-1.92958393e-03, -1.30703226e+00,  1.00772212e+00, ...,
        -7.74596669e-01, -7.24518244e-01, -4.51335467e-01]])

In [27]:
#Splitting data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [28]:
print("train data size (features):",len(x_train))
print("train data size (target):",len(y_train))

print("test data size (features):",len(x_test))
print("test data size (target):",len(y_test))

train data size (features): 416
train data size (target): 416
test data size (features): 104
test data size (target): 104


# **Model**

**Support Vector Classifier - SVC**
https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html


**K Fold Cross Validation**

In [30]:
from sklearn.svm import SVC
SVC_model = SVC(C=0.5, kernel = 'poly', degree=2, gamma ='scale', coef0=0.0, tol = 0.0001, decision_function_shape='ovr')

In [31]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold

k_fold = KFold(10)

accuracy = cross_val_score(SVC_model,x_train,y_train,cv=k_fold,scoring='accuracy')
precision = cross_val_score(SVC_model,x_train,y_train,cv=k_fold,scoring='precision')
recall = cross_val_score(SVC_model,x_train,y_train,cv=k_fold,scoring='recall')
f1_score = cross_val_score(SVC_model,x_train,y_train,cv=k_fold,scoring='f1')
AUC = cross_val_score(SVC_model,x_train,y_train,cv=k_fold,scoring='roc_auc')

- 10 fold, so 9 fold is for train partition and 1 fold is for validation  
- Validation partition is used for tuning hyperparameters

In [32]:
accuracy

array([0.95238095, 0.88095238, 0.9047619 , 0.73809524, 0.88095238,
       0.9047619 , 0.85365854, 0.97560976, 0.82926829, 0.87804878])

In [33]:
# average accuracy
overall_accuracy = sum(accuracy)/ len(accuracy)
print(overall_accuracy)

0.8798490127758422


In [35]:
precision

array([0.96428571, 0.84615385, 0.93103448, 0.84      , 0.86206897,
       0.83333333, 0.84      , 0.96153846, 0.85      , 0.91304348])

In [36]:
overall_precision = sum(precision)/ len(precision)
print(overall_precision)

0.8841458281848086


In [37]:
recall

array([0.96428571, 0.95652174, 0.93103448, 0.75      , 0.96153846,
       1.        , 0.91304348, 1.        , 0.80952381, 0.875     ])

In [38]:
overall_recall = sum(recall)/ len(recall)
print(overall_recall)

0.9160947685497909


In [39]:
f1_score

array([0.96428571, 0.89795918, 0.93103448, 0.79245283, 0.90909091,
       0.90909091, 0.875     , 0.98039216, 0.82926829, 0.89361702])

In [40]:
overall_f1_score = sum(f1_score)/ len(f1_score)
print(overall_f1_score)

0.898219149991057


In [41]:
AUC

array([0.96428571, 0.95194508, 0.97082228, 0.90306122, 0.96634615,
       0.97272727, 0.93236715, 0.995     , 0.82380952, 0.92892157])

In [42]:
overall_AUC = sum(AUC)/ len(AUC)
print(overall_AUC)

0.9409285968803008


**Test Performance**

In [43]:
SVC_model = SVC(C=0.5, kernel = 'poly', degree=2, gamma ='scale', coef0=0.0, tol = 0.0001, decision_function_shape='ovr')
SVC_model.fit(x_train,y_train)

SVC(C=0.5, degree=2, kernel='poly', tol=0.0001)

In [44]:
pred_values = SVC_model.predict(x_test)

In [45]:
from sklearn.metrics import accuracy_score , precision_score , recall_score , f1_score , roc_auc_score , roc_curve

**All of these are needed to evaluate classification problem**

In [46]:
accuracy_test = accuracy_score(y_test,pred_values)
precision_test = precision_score(y_test,pred_values)
recall_test = recall_score(y_test,pred_values)
f1_test = f1_score(y_test,pred_values)
AUC_test = roc_auc_score(y_test,pred_values) # area under the curve

print("Accuracy:",accuracy_test)
print("Precision:",precision_test)
print("Recall:",recall_test)
print("F1:",f1_test)
print("AUC:",AUC_test)

Accuracy: 0.9326923076923077
Precision: 0.9583333333333334
Recall: 0.9452054794520548
F1: 0.9517241379310345
AUC: 0.9242156429518339
